"""schema inicial

Revision ID: f8aa8f5dd94a
Revises: 
Create Date: 2026-07-29 19:10:48.856083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8aa8f5dd94a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comanda',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('id_cliente', sa.Uuid(), nullable=True),
    sa.Column('identificador', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'PAGA', 'CANCELADA', name='statuscomanda'), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('aberta_em', sa.DateTime(), nullable=False),
    sa.Column('fechada_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_cancelamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origem_externa', sa.Enum('SALAO', 'IFOOD', 'WHATSAPP', name='origempedido'), nullable=True),
    sa.Column('id_referencia_externa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comanda_id_cliente'), 'comanda', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_comanda_id_loja'), 'comanda', ['id_loja'], unique=False)
    op.create_index(op.f('ix_comanda_id_referencia_externa'), 'comanda', ['id_referencia_externa'], unique=False)
    op.create_index(op.f('ix_comanda_origem_externa'), 'comanda', ['origem_externa'], unique=False)
    op.create_table('operador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN', 'GERENTE', 'CAIXA', 'COZINHA', 'GARCOM', name='papeloperador'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operador_email'), 'operador', ['email'], unique=True)
    op.create_index(op.f('ix_operador_id_loja'), 'operador', ['id_loja'], unique=False)
    op.create_table('item_comanda',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('id_comanda', sa.Uuid(), nullable=False),
    sa.Column('id_produto', sa.Uuid(), nullable=False),
    sa.Column('nome_produto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('preco_aplicado', sa.Float(), nullable=False),
    sa.Column('origem', sa.Enum('SALAO', 'IFOOD', 'WHATSAPP', name='origempedido'), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_comanda_id_comanda'), 'item_comanda', ['id_comanda'], unique=False)
    op.create_index(op.f('ix_item_comanda_id_loja'), 'item_comanda', ['id_loja'], unique=False)
    op.create_table('ticket_producao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('id_item_comanda', sa.Uuid(), nullable=False),
    sa.Column('status_producao', sa.Enum('PENDENTE', 'EM_PREPARO', 'PRONTO', 'ENTREGUE', name='statusproducao'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_item_comanda'], ['item_comanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_producao_id_item_comanda'), 'ticket_producao', ['id_item_comanda'], unique=False)
    op.create_index(op.f('ix_ticket_producao_id_loja'), 'ticket_producao', ['id_loja'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_producao_id_loja'), table_name='ticket_producao')
    op.drop_index(op.f('ix_ticket_producao_id_item_comanda'), table_name='ticket_producao')
    op.drop_table('ticket_producao')
    op.drop_index(op.f('ix_item_comanda_id_loja'), table_name='item_comanda')
    op.drop_index(op.f('ix_item_comanda_id_comanda'), table_name='item_comanda')
    op.drop_table('item_comanda')
    op.drop_index(op.f('ix_operador_id_loja'), table_name='operador')
    op.drop_index(op.f('ix_operador_email'), table_name='operador')
    op.drop_table('operador')
    op.drop_index(op.f('ix_comanda_origem_externa'), table_name='comanda')
    op.drop_index(op.f('ix_comanda_id_referencia_externa'), table_name='comanda')
    op.drop_index(op.f('ix_comanda_id_loja'), table_name='comanda')
    op.drop_index(op.f('ix_comanda_id_cliente'), table_name='comanda')
    op.drop_table('comanda')
    # ### end Alembic commands ###
