"""schema inicial

Revision ID: f161c675d33b
Revises: 
Create Date: 2026-07-29 19:10:45.532205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f161c675d33b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loja',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pontos_fidelidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_cpf'), 'cliente', ['cpf'], unique=False)
    op.create_index(op.f('ix_cliente_id_loja'), 'cliente', ['id_loja'], unique=False)
    op.create_table('fechamento_caixa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('aberto_em', sa.DateTime(), nullable=False),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fechamento_caixa_id_loja'), 'fechamento_caixa', ['id_loja'], unique=False)
    op.create_table('insumo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unidade_medida', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.Column('qtd_estoque', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insumo_id_loja'), 'insumo', ['id_loja'], unique=False)
    op.create_table('produto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativo_venda', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_id_loja'), 'produto', ['id_loja'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN', 'GERENTE', 'CAIXA', 'COZINHA', 'GARCOM', name='papelusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id_loja'), 'usuario', ['id_loja'], unique=False)
    op.create_table('ficha_tecnica',
    sa.Column('id_produto', sa.Uuid(), nullable=False),
    sa.Column('id_insumo', sa.Uuid(), nullable=False),
    sa.Column('qtd_utilizada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id_produto', 'id_insumo')
    )
    op.create_table('movimento_estoque',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_loja', sa.Uuid(), nullable=False),
    sa.Column('id_insumo', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA_VENDA', 'AJUSTE', name='tipomovimentoestoque'), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('referencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimento_estoque_id_insumo'), 'movimento_estoque', ['id_insumo'], unique=False)
    op.create_index(op.f('ix_movimento_estoque_id_loja'), 'movimento_estoque', ['id_loja'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimento_estoque_id_loja'), table_name='movimento_estoque')
    op.drop_index(op.f('ix_movimento_estoque_id_insumo'), table_name='movimento_estoque')
    op.drop_table('movimento_estoque')
    op.drop_table('ficha_tecnica')
    op.drop_index(op.f('ix_usuario_id_loja'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_produto_id_loja'), table_name='produto')
    op.drop_table('produto')
    op.drop_index(op.f('ix_insumo_id_loja'), table_name='insumo')
    op.drop_table('insumo')
    op.drop_index(op.f('ix_fechamento_caixa_id_loja'), table_name='fechamento_caixa')
    op.drop_table('fechamento_caixa')
    op.drop_index(op.f('ix_cliente_id_loja'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_cpf'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_table('loja')
    # ### end Alembic commands ###
