/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { LoginRequest } from '../model/models';
import { RegisterRequest } from '../model/models';
import { TokenResponse } from '../model/models';
import { UserOut } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Login
     * 
     * @endpoint post /api/auth/login
     * @param loginRequest 
     */
    loginApiAuthLoginPost(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<TokenResponse>;

    /**
     * Me
     * 
     * @endpoint get /api/me
     */
    meApiMeGet(extraHttpRequestParams?: any): Observable<UserOut>;

    /**
     * Refresh
     * 
     * @endpoint post /api/auth/refresh
     * @param refreshToken 
     */
    refreshApiAuthRefreshPost(refreshToken?: string, extraHttpRequestParams?: any): Observable<TokenResponse>;

    /**
     * Register
     * 
     * @endpoint post /api/auth/register
     * @param registerRequest 
     */
    registerApiAuthRegisterPost(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<UserOut>;

}
