/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CartItemCreate } from '../model/models';
import { CartItemUpdate } from '../model/models';
import { CartOut } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CartServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add Item
     * 
     * @endpoint post /api/cart/items
     * @param cartItemCreate 
     */
    addItemApiCartItemsPost(cartItemCreate: CartItemCreate, extraHttpRequestParams?: any): Observable<CartOut>;

    /**
     * Get Cart
     * 
     * @endpoint get /api/cart
     */
    getCartApiCartGet(extraHttpRequestParams?: any): Observable<CartOut>;

    /**
     * Remove Item
     * 
     * @endpoint delete /api/cart/items/{item_id}
     * @param itemId 
     */
    removeItemApiCartItemsItemIdDelete(itemId: string, extraHttpRequestParams?: any): Observable<CartOut>;

    /**
     * Update Item
     * 
     * @endpoint patch /api/cart/items/{item_id}
     * @param itemId 
     * @param cartItemUpdate 
     */
    updateItemApiCartItemsItemIdPatch(itemId: string, cartItemUpdate: CartItemUpdate, extraHttpRequestParams?: any): Observable<CartOut>;

}
