/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChatMessageOut } from '../model/models';
import { ChatRequest } from '../model/models';
import { ChatResponse } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ChatServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Chat
     * 
     * @endpoint post /api/chat
     * @param chatRequest 
     */
    chatApiChatPost(chatRequest: ChatRequest, extraHttpRequestParams?: any): Observable<ChatResponse>;

    /**
     * History
     * 
     * @endpoint get /api/chat/history
     */
    historyApiChatHistoryGet(extraHttpRequestParams?: any): Observable<Array<ChatMessageOut>>;

}
