/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { OrderOut } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OrdersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Checkout
     * 
     * @endpoint post /api/checkout
     */
    createCheckoutApiCheckoutPost(extraHttpRequestParams?: any): Observable<OrderOut>;

    /**
     * Get Order
     * 
     * @endpoint get /api/orders/{order_id}
     * @param orderId 
     */
    getOrderApiOrdersOrderIdGet(orderId: string, extraHttpRequestParams?: any): Observable<OrderOut>;

    /**
     * List Orders
     * 
     * @endpoint get /api/orders
     */
    listOrdersApiOrdersGet(extraHttpRequestParams?: any): Observable<Array<OrderOut>>;

}
