/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { ProductCreate } from '../model/models';
import { ProductListOut } from '../model/models';
import { ProductOut } from '../model/models';
import { ProductUpdate } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Product
     * 
     * @endpoint post /api/products
     * @param productCreate 
     */
    createProductApiProductsPost(productCreate: ProductCreate, extraHttpRequestParams?: any): Observable<ProductOut>;

    /**
     * Get Product
     * 
     * @endpoint get /api/products/{product_id}
     * @param productId 
     */
    getProductApiProductsProductIdGet(productId: string, extraHttpRequestParams?: any): Observable<ProductOut>;

    /**
     * List Products
     * 
     * @endpoint get /api/products
     * @param q Free-text search on title/description
     * @param category 
     * @param minPriceCents 
     * @param maxPriceCents 
     * @param limit 
     * @param offset 
     */
    listProductsApiProductsGet(q?: string, category?: string, minPriceCents?: number, maxPriceCents?: number, limit?: number, offset?: number, extraHttpRequestParams?: any): Observable<ProductListOut>;

    /**
     * Update Product
     * 
     * @endpoint patch /api/products/{product_id}
     * @param productId 
     * @param productUpdate 
     */
    updateProductApiProductsProductIdPatch(productId: string, productUpdate: ProductUpdate, extraHttpRequestParams?: any): Observable<ProductOut>;

}
