/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { ReviewCreate } from '../model/models';
import { ReviewOut } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReviewsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Review
     * 
     * @endpoint post /api/products/{product_id}/reviews
     * @param productId 
     * @param reviewCreate 
     */
    createReviewApiProductsProductIdReviewsPost(productId: string, reviewCreate: ReviewCreate, extraHttpRequestParams?: any): Observable<ReviewOut>;

    /**
     * List Reviews
     * 
     * @endpoint get /api/products/{product_id}/reviews
     * @param productId 
     */
    listReviewsApiProductsProductIdReviewsGet(productId: string, extraHttpRequestParams?: any): Observable<Array<ReviewOut>>;

}
