/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProductOut } from '../model/models';
import { SellerDashboard } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SellerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Dashboard
     * 
     * @endpoint get /api/seller/dashboard
     */
    dashboardApiSellerDashboardGet(extraHttpRequestParams?: any): Observable<SellerDashboard>;

    /**
     * My Products
     * 
     * @endpoint get /api/seller/products
     */
    myProductsApiSellerProductsGet(extraHttpRequestParams?: any): Observable<Array<ProductOut>>;

    /**
     * Received Orders
     * 
     * @endpoint get /api/seller/orders
     */
    receivedOrdersApiSellerOrdersGet(extraHttpRequestParams?: any): Observable<any>;

}
