/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { ShipmentOut } from '../model/models';
import { TrackingOut } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ShippingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Advance Shipment
     * 
     * @endpoint patch /api/shipments/{shipment_id}/advance
     * @param shipmentId 
     */
    advanceShipmentApiShipmentsShipmentIdAdvancePatch(shipmentId: string, extraHttpRequestParams?: any): Observable<ShipmentOut>;

    /**
     * Track
     * 
     * @endpoint get /api/shipments/track/{code}
     * @param code 
     */
    trackApiShipmentsTrackCodeGet(code: string, extraHttpRequestParams?: any): Observable<TrackingOut>;

}
