/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductOut } from './productOut';


export interface CartItemOut { 
    id: string;
    product_id: string;
    quantity: number;
    product: ProductOut;
    line_total_cents: number;
}

