/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartItemOut } from './cartItemOut';


export interface CartOut { 
    items: Array<CartItemOut>;
    total_cents: number;
}

