/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatRole } from './chatRole';


export interface ChatMessageOut { 
    id: string;
    role: ChatRole;
    content: string;
    order_id: string | null;
    created_at: string;
}
export namespace ChatMessageOut {
}


