/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMessageOut } from './chatMessageOut';


export interface ChatResponse { 
    reply: ChatMessageOut;
}

