/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipmentOut } from './shipmentOut';
import { OrderStatus } from './orderStatus';
import { OrderItemOut } from './orderItemOut';
import { PaymentStatus } from './paymentStatus';


export interface OrderOut { 
    id: string;
    buyer_id: string;
    total_cents: number;
    status: OrderStatus;
    payment_status: PaymentStatus;
    created_at: string;
    items: Array<OrderItemOut>;
    shipment?: ShipmentOut | null;
}
export namespace OrderOut {
}


