/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderItemOut { 
    id: string;
    product_id: string;
    title_snapshot: string;
    unit_price_cents: number;
    quantity: number;
}

