/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductStatus } from './productStatus';


export interface ProductUpdate { 
    title?: string | null;
    description?: string | null;
    price_cents?: number | null;
    stock?: number | null;
    category?: string | null;
    images?: Array<string> | null;
    status?: ProductStatus | null;
}
export namespace ProductUpdate {
}


