/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductOut } from './productOut';


export interface ProductListOut { 
    items: Array<ProductOut>;
    total: number;
    limit: number;
    offset: number;
}

