/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductCreate { 
    title: string;
    description?: string;
    price_cents: number;
    currency?: string;
    stock: number;
    category: string;
    images?: Array<string>;
}

