/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductStatus } from './productStatus';
import { SellerInfo } from './sellerInfo';


export interface ProductOut { 
    id: string;
    seller_id: string;
    title: string;
    description: string;
    price_cents: number;
    currency: string;
    stock: number;
    category: string;
    images: Array<string>;
    status: ProductStatus;
    created_at: string;
    seller?: SellerInfo | null;
}
export namespace ProductOut {
}


