/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ProductStatus = {
    Active: 'ACTIVE',
    Paused: 'PAUSED'
} as const;
export type ProductStatus = typeof ProductStatus[keyof typeof ProductStatus];

