/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface RegisterRequest { 
    name: string;
    email: string;
    password: string;
    role?: UserRole;
    store_name?: string | null;
}
export namespace RegisterRequest {
}


