/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewOut { 
    id: string;
    product_id: string;
    buyer_id: string;
    rating: number;
    comment: string;
    created_at: string;
}

