/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SellerDashboard { 
    store_name: string;
    reputation_score: number;
    active_products: number;
    total_orders: number;
    revenue_cents: number;
}

