/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipmentStatus } from './shipmentStatus';


export interface ShipmentOut { 
    id: string;
    order_id: string;
    status: ShipmentStatus;
    tracking_code: string;
    estimated_delivery: string | null;
    updated_at: string;
}
export namespace ShipmentOut {
}


