/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipmentStatus } from './shipmentStatus';


export interface TrackingEvent { 
    status: ShipmentStatus;
    label: string;
    reached: boolean;
}
export namespace TrackingEvent {
}


