/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrackingEvent } from './trackingEvent';
import { ShipmentStatus } from './shipmentStatus';


export interface TrackingOut { 
    tracking_code: string;
    current_status: ShipmentStatus;
    estimated_delivery: string | null;
    timeline: Array<TrackingEvent>;
}
export namespace TrackingOut {
}


