/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface UserOut { 
    id: string;
    name: string;
    email: string;
    role: UserRole;
    created_at: string;
    seller_id?: string | null;
}
export namespace UserOut {
}


