/**
 * E-commerce MVP
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const UserRole = {
    Buyer: 'BUYER',
    Seller: 'SELLER',
    Admin: 'ADMIN'
} as const;
export type UserRole = typeof UserRole[keyof typeof UserRole];

