-- 1. Tabela de Insumos (Matéria-prima do estoque)
CREATE TABLE INSUMO (
    ID_INSUMO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(100) NOT NULL,
    UNIDADE_MEDIDA VARCHAR2(10) NOT NULL, -- Ex: 'L', 'KG', 'UN'
    CUSTO_UNITARIO NUMBER(10,4) NOT NULL,
    QTD_ESTOQUE NUMBER(10,4) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_INSUMO PRIMARY KEY (ID_INSUMO)
);

-- 2. Tabela de Produtos (O que é vendido ao cliente final)
CREATE TABLE PRODUTO (
    ID_PRODUTO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(100) NOT NULL,
    PRECO_VENDA NUMBER(10,2) NOT NULL,
    CATEGORIA VARCHAR2(50),
    ATIVO_VENDA CHAR(1) DEFAULT 'S' NOT NULL, -- 'S' para Sim, 'N' para Não
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO)
);

-- 3. Tabela Ficha Técnica (Relacionamento N:N entre Produto e Insumo)
CREATE TABLE FICHA_TECNICA (
    ID_PRODUTO NUMBER NOT NULL,
    ID_INSUMO NUMBER NOT NULL,
    QTD_UTILIZADA NUMBER(10,4) NOT NULL,
    CONSTRAINT PK_FICHA_TECNICA PRIMARY KEY (ID_PRODUTO, ID_INSUMO),
    CONSTRAINT FK_FT_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
    CONSTRAINT FK_FT_INSUMO FOREIGN KEY (ID_INSUMO) REFERENCES INSUMO(ID_INSUMO)
);

-- 4. Tabela de Comanda (Agrupador financeiro da mesa/cliente)
CREATE TABLE COMANDA (
    ID_COMANDA NUMBER GENERATED ALWAYS AS IDENTITY,
    IDENTIFICADOR VARCHAR2(50) NOT NULL, -- Ex: 'MESA 04', 'SENHA 102'
    STATUS VARCHAR2(20) DEFAULT 'ABERTA' NOT NULL, -- 'ABERTA', 'PAGA', 'CANCELADA'
    VALOR_TOTAL NUMBER(10,2) DEFAULT 0 NOT NULL,
    DATA_ABERTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_COMANDA PRIMARY KEY (ID_COMANDA)
);

-- 5. Tabela de Item da Comanda (O registro individual das vendas)
CREATE TABLE ITEM_COMANDA (
    ID_ITEM NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_COMANDA NUMBER NOT NULL,
    ID_PRODUTO NUMBER NOT NULL,
    QTD NUMBER(10,3) NOT NULL,
    PRECO_APLICADO NUMBER(10,2) NOT NULL,
    ORIGEM VARCHAR2(20) NOT NULL, -- Ex: 'IFOOD', 'WHATSAPP', 'SALAO'
    CONSTRAINT PK_ITEM_COMANDA PRIMARY KEY (ID_ITEM),
    CONSTRAINT FK_ITEM_COMANDA FOREIGN KEY (ID_COMANDA) REFERENCES COMANDA(ID_COMANDA),
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);
